name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Publish the site
      - name: Publish
        run: |
            cp RingLight/wwwroot/index.html RingLight/wwwroot/404.html
            dotnet publish RingLight/RingLight.csproj -c Release -o output --nologo

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/wwwroot
          force_orphan: true
          keep_files: false
          # TODO uncomment the following line if you have a custom domain name
          cname: ringlight.nielsen.tech
